enum NVME_LOG_PAGES : uint
{
	NVME_LOG_PAGE_ERROR_INFO = 0x01,
	NVME_LOG_PAGE_HEALTH_INFO,
	NVME_LOG_PAGE_FIRMWARE_SLOT_INFO,
	NVME_LOG_PAGE_CHANGED_NAMESPACE_LIST,
	NVME_LOG_PAGE_COMMAND_EFFECTS,
	NVME_LOG_PAGE_DEVICE_SELF_TEST,
	NVME_LOG_PAGE_TELEMETRY_HOST_INITIATED,
	NVME_LOG_PAGE_TELEMETRY_CTLR_INITIATED,
	NVME_LOG_PAGE_ENDURANCE_GROUP_INFORMATION,
	NVME_LOG_PAGE_RESERVATION_NOTIFICATION = 0x80,
	NVME_LOG_PAGE_SANITIZE_STATUS,
}
