enum STORAGE_BUS_TYPE : uint
{
	BusTypeUnknown,
	BusTypeScsi,
	BusTypeAtapi,
	BusTypeAta,
	BusType1394,
	BusTypeSsa,
	BusTypeFibre,
	BusTypeUsb,
	BusTypeRAID,
	BusTypeiScsi,
	BusTypeSas,
	BusTypeSata,
	BusTypeSd,
	BusTypeMmc,
	BusTypeVirtual,
	BusTypeFileBackedVirtual,
	BusTypeSpaces,
	BusTypeNvme,
	BusTypeSCM,
	BusTypeUfs,
	BusTypeMax,
	BusTypeMaxReserved = 0x7F,
}
